SET SERVEROUTPUT ON;
SET DEFINE OFF;


--@country_master_data.sql
DECLARE
-- バインド変数の定義
v_country_data t_country_tab;
-- データの初期化と代入
BEGIN
    v_country_data := t_country_tab(

		t_country_obj(q'[アイスランド]',  q'[Iceland]', 354),
		t_country_obj(q'[アイルランド]',  q'[Ireland]', 353),
		t_country_obj(q'[アゼルバイジャン]',  q'[Azerbaidjan]', 994),
		t_country_obj(q'[アセンション島]',  q'[Ascension]', 247),
		t_country_obj(q'[アゾレス諸島]',  q'[Azores Islands]', 351),
		t_country_obj(q'[アフガニスタン]',  q'[Afghanistan]', 93),
		t_country_obj(q'[アメリカ (本土)]',  q'[U.S.A.]', 1),
		t_country_obj(q'[アラスカ]',  q'[Alaska]', 1),
		t_country_obj(q'[アラスカ]',  q'[Alaska]', 907),
		t_country_obj(q'[アラブ首長国連邦]',  q'[U.A.E.]', 971),
		t_country_obj(q'[アルジェリア]',  q'[Algeria]', 213),
		t_country_obj(q'[アルゼンチン]',  q'[Argentina]', 54),
		t_country_obj(q'[アルバ]',  q'[Aruba]', 297),
		t_country_obj(q'[アルバニア]',  q'[Albania]', 355),
		t_country_obj(q'[アルメニア]',  q'[Armenia]', 374),
		t_country_obj(q'[アンギラ]',  q'[Anguilla]', 1),
		t_country_obj(q'[アンギラ]',  q'[Anguilla]', 264),
		t_country_obj(q'[アンゴラ]',  q'[Angola]', 244),
		t_country_obj(q'[アンティグア・バーブーダ]',  q'[Antigua & Barbuda]', 1),
		t_country_obj(q'[アンティグア・バーブーダ]',  q'[Antigua & Barbuda]', 268),
		t_country_obj(q'[アンドラ]',  q'[Andorra]', 376),
		t_country_obj(q'[イエメン]',  q'[Yemen]', 967),
		t_country_obj(q'[イギリス]',  q'[U.K.]', 44),
		t_country_obj(q'[イスラエル]',  q'[Israel]', 972),
		t_country_obj(q'[イタリア]',  q'[Italy]', 39),
		t_country_obj(q'[イラク]',  q'[Iraq]', 964),
		t_country_obj(q'[イラン]',  q'[Iran]', 98),
		t_country_obj(q'[インド]',  q'[India]', 91),
		t_country_obj(q'[インドネシア]',  q'[Indonesia]', 62),
		t_country_obj(q'[ウガンダ]',  q'[Uganda]', 256),
		t_country_obj(q'[ウクライナ]',  q'[Ukraine]', 380),
		t_country_obj(q'[ウズベキスタン]',  q'[Uzbekistan]', 998),
		t_country_obj(q'[ウルグアイ]',  q'[Uruguay]', 598),
		t_country_obj(q'[エクアドル]',  q'[Ecuador]', 593),
		t_country_obj(q'[エジプト]',  q'[Egypt]', 20),
		t_country_obj(q'[エストニア]',  q'[Estonia]', 372),
		t_country_obj(q'[エスワティニ]',  q'[eSwatini]', 268),
		t_country_obj(q'[エチオピア]',  q'[Ethiopia]', 251),
		t_country_obj(q'[エリトリア]',  q'[Eritrea]', 291),
		t_country_obj(q'[エルサルバドル]',  q'[El Salvador]', 503),
		t_country_obj(q'[オーストラリア]',  q'[Australia]', 61),
		t_country_obj(q'[オーストリア]',  q'[Austria]', 43),
		t_country_obj(q'[オマーン]',  q'[Oman]', 968),
		t_country_obj(q'[オランダ]',  q'[Netherlands]', 31),
		t_country_obj(q'[オランダ領アンティール]',  q'[Netherlands Antilles]', 599),
		t_country_obj(q'[ガーナ]',  q'[Ghana]', 233),
		t_country_obj(q'[カーボベルデ]',  q'[Cape Verde]', 238),
		t_country_obj(q'[ガイアナ]',  q'[Guyana]', 592),
		t_country_obj(q'[カザフスタン]',  q'[Kazakhstan]', 7),
		t_country_obj(q'[カタール]',  q'[Qatar]', 974),
		t_country_obj(q'[カナダ]',  q'[Canada]', 1),
		t_country_obj(q'[カナリア諸島]',  q'[Canary Islands]', 34),
		t_country_obj(q'[ガボン]',  q'[Gabon]', 241),
		t_country_obj(q'[カメルーン]',  q'[Cameroon]', 237),
		t_country_obj(q'[ガンビア]',  q'[Gambia]', 220),
		t_country_obj(q'[カンボジア]',  q'[Cambodia]', 855),
		t_country_obj(q'[ギニア]',  q'[Guinea]', 224),
		t_country_obj(q'[ギニアビサウ]',  q'[GuineaBissau]', 245),
		t_country_obj(q'[キプロス]',  q'[Cyprus]', 357),
		t_country_obj(q'[キューバ]',  q'[Cuba]', 53),
		t_country_obj(q'[ギリシア]',  q'[Greece]', 30),
		t_country_obj(q'[キリバス]',  q'[Kiribati]', 686),
		t_country_obj(q'[キルギスタン]',  q'[Kyrgyz Rep.]', 996),
		t_country_obj(q'[グアテマラ]',  q'[Guatemala]', 502),
		t_country_obj(q'[グアドループ島（仏領サン・マルタン、サン・バルテルミー島含む）]',  q'[Guadeloupe (inc. French St. Martin and St. Bart)]', 590),
		t_country_obj(q'[グアム]',  q'[Guam]', 1),
		t_country_obj(q'[グアム]',  q'[Guam]', 671),
		t_country_obj(q'[クウェート]',  q'[Kuwait]', 965),
		t_country_obj(q'[クック諸島]',  q'[Cook Islands]', 682),
		t_country_obj(q'[グリーンランド]',  q'[Greenland]', 299),
		t_country_obj(q'[クリスマス島]',  q'[Christmas Is.]', 61),
		t_country_obj(q'[グレナダ]',  q'[Grenada]', 1),
		t_country_obj(q'[グレナダ]',  q'[Grenada]', 473),
		t_country_obj(q'[クロアチア]',  q'[Croatia]', 385),
		t_country_obj(q'[ケイマン諸島]',  q'[Cayman Islands]', 1),
		t_country_obj(q'[ケイマン諸島]',  q'[Cayman Islands]', 345),
		t_country_obj(q'[ケニア]',  q'[Kenya]', 254),
		t_country_obj(q'[コートジボワール]',  q'[Cote d'lvoire]', 225),
		t_country_obj(q'[ココス諸島]',  q'[Cocos Keeling Is.]', 61),
		t_country_obj(q'[コスタリカ]',  q'[Costa Rica]', 506),
		t_country_obj(q'[コソボ]',  q'[Kosovo]', 383),
		t_country_obj(q'[コモロ]',  q'[Comoros]', 269),
		t_country_obj(q'[コロンビア]',  q'[Colombia]', 57),
		t_country_obj(q'[コンゴ]',  q'[Congo(Rep. of)]', 242),
		t_country_obj(q'[コンゴ民主共和国]',  q'[Congo (Demo.)]', 243),
		t_country_obj(q'[サイパン]',  q'[Saipan]', 1),
		t_country_obj(q'[サイパン]',  q'[Saipan]', 670),
		t_country_obj(q'[サウジアラビア]',  q'[Saudi Arabia]', 966),
		t_country_obj(q'[サモア]',  q'[Samoa]', 685),
		t_country_obj(q'[サントメ・プリンシペ]',  q'[Sao Tome & Principe]', 239),
		t_country_obj(q'[ザンビア]',  q'[Zambia]', 260),
		t_country_obj(q'[サンピエール島・ミクロン島]',  q'[St. Pierre & Miquelo]', 508),
		t_country_obj(q'[サンマリノ]',  q'[San Marino]', 378),
		t_country_obj(q'[シエラレオネ]',  q'[Sierra Leone]', 232),
		t_country_obj(q'[ジブチ]',  q'[Djibouti]', 253),
		t_country_obj(q'[ジブラルタル]',  q'[Gibraltar]', 350),
		t_country_obj(q'[ジャマイカ]',  q'[Jamaica]', 1),
		t_country_obj(q'[ジャマイカ]',  q'[Jamaica]', 658),
		t_country_obj(q'[ジャマイカ]',  q'[Jamaica]', 876),
		t_country_obj(q'[ジョージア]',  q'[Georgia]', 995),
		t_country_obj(q'[シリア]',  q'[Syria]', 963),
		t_country_obj(q'[シンガポール]',  q'[Singapore]', 65),
		t_country_obj(q'[シント・マールテン]',  q'[Saint Martin]', 1),
		t_country_obj(q'[シント・マールテン]',  q'[Saint Martin]', 721),
		t_country_obj(q'[ジンバブエ]',  q'[Zimbabwe]', 263),
		t_country_obj(q'[スイス]',  q'[Switzerland]', 41),
		t_country_obj(q'[スウェーデン]',  q'[Sweden]', 46),
		t_country_obj(q'[スーダン]',  q'[Sudan]', 249),
		t_country_obj(q'[スペイン]',  q'[Spain]', 34),
		t_country_obj(q'[スペイン領北アフリカ]',  q'[Spanish North Africa]', 34),
		t_country_obj(q'[スラーヤーテレコム]',  q'[Thuraya Satellite]', 88216),
		t_country_obj(q'[スリナム]',  q'[Suriname]', 597),
		t_country_obj(q'[スリランカ]',  q'[Sri Lanka]', 94),
		t_country_obj(q'[スロバキア]',  q'[Slovak]', 421),
		t_country_obj(q'[スロベニア]',  q'[Slovenia]', 386),
		t_country_obj(q'[セーシェル]',  q'[Seychelles]', 248),
		t_country_obj(q'[セネガル]',  q'[Senegal]', 221),
		t_country_obj(q'[セルビア]',  q'[Serbia]', 381),
		t_country_obj(q'[セントクリストファー・ネイビス]',  q'[St. Christopher & Ne]', 1),
		t_country_obj(q'[セントクリストファー・ネイビス]',  q'[St. Christopher & Ne]', 869),
		t_country_obj(q'[セントビンセントおよびグレナディーン諸島]',  q'[St. Vincent & the Gr]', 1),
		t_country_obj(q'[セントビンセントおよびグレナディーン諸島]',  q'[St. Vincent & the Gr]', 784),
		t_country_obj(q'[セントヘレナ島]',  q'[St. Helena]', 290),
		t_country_obj(q'[セントルシア]',  q'[St. Lucia]', 1),
		t_country_obj(q'[セントルシア]',  q'[St. Lucia]', 758),
		t_country_obj(q'[ソマリア]',  q'[Somalia]', 252),
		t_country_obj(q'[ソロモン諸島]',  q'[Solomon Is.]', 677),
		t_country_obj(q'[タークス諸島・カイコス諸島]',  q'[Turks & Caicos Is.]', 1),
		t_country_obj(q'[タークス諸島・カイコス諸島]',  q'[Turks & Caicos Is.]', 649),
		t_country_obj(q'[タイ]',  q'[Thailand]', 66),
		t_country_obj(q'[タジキスタン]',  q'[Tadzhikistan]', 992),
		t_country_obj(q'[タンザニア]',  q'[Tanzania]', 255),
		t_country_obj(q'[チェコ]',  q'[Czech]', 420),
		t_country_obj(q'[チャド]',  q'[Chad]', 235),
		t_country_obj(q'[チュニジア]',  q'[Tunisia]', 216),
		t_country_obj(q'[チリ]',  q'[Chile]', 56),
		t_country_obj(q'[ツバル]',  q'[Tuvalu]', 688),
		t_country_obj(q'[デンマーク]',  q'[Denmark]', 45),
		t_country_obj(q'[ドイツ]',  q'[Germany]', 49),
		t_country_obj(q'[トーゴ]',  q'[Togo]', 228),
		t_country_obj(q'[トケラウ諸島]',  q'[Tokelau Islands]', 690),
		t_country_obj(q'[ドミニカ]',  q'[Dominica]', 1),
		t_country_obj(q'[ドミニカ]',  q'[Dominica]', 767),
		t_country_obj(q'[ドミニカ共和国]',  q'[Dominican Rep.]', 1),
		t_country_obj(q'[ドミニカ共和国]',  q'[Dominican Rep.]', 809),
		t_country_obj(q'[ドミニカ共和国]',  q'[Dominican Rep.]', 829),
		t_country_obj(q'[ドミニカ共和国]',  q'[Dominican Rep.]', 849),
		t_country_obj(q'[トリニダード・トバゴ]',  q'[Trinidad & Tobago]', 1),
		t_country_obj(q'[トリニダード・トバゴ]',  q'[Trinidad & Tobago]', 868),
		t_country_obj(q'[トルクメニスタン]',  q'[Turkmenistan]', 993),
		t_country_obj(q'[トルコ]',  q'[Turkey]', 90),
		t_country_obj(q'[トンガ]',  q'[Tonga]', 676),
		t_country_obj(q'[ナイジェリア]',  q'[Nigeria]', 234),
		t_country_obj(q'[ナウル]',  q'[Nauru]', 674),
		t_country_obj(q'[ナミビア]',  q'[Namibia]', 264),
		t_country_obj(q'[ニウエ]',  q'[Niue]', 683),
		t_country_obj(q'[ニカラグア]',  q'[Nicaragua]', 505),
		t_country_obj(q'[ニジェール]',  q'[Niger]', 227),
		t_country_obj(q'[ニューカレドニア]',  q'[New Caledonia]', 687),
		t_country_obj(q'[ニュージーランド]',  q'[New Zealand]', 64),
		t_country_obj(q'[ネパール]',  q'[Nepal]', 977),
		t_country_obj(q'[ノーフォーク島]',  q'[Norfolk Island]', 672),
		t_country_obj(q'[ノルウェー]',  q'[Norway]', 47),
		t_country_obj(q'[バーレーン]',  q'[Bahrain]', 973),
		t_country_obj(q'[ハイチ]',  q'[Haiti]', 509),
		t_country_obj(q'[パキスタン]',  q'[Pakistan]', 92),
		t_country_obj(q'[バチカン]',  q'[Vatican City]', 39),
		t_country_obj(q'[パナマ]',  q'[Panama]', 507),
		t_country_obj(q'[バヌアツ]',  q'[Vanuatu]', 678),
		t_country_obj(q'[バハマ]',  q'[Bahamas]', 1),
		t_country_obj(q'[バハマ]',  q'[Bahamas]', 242),
		t_country_obj(q'[パプアニューギニア]',  q'[Papua New Guinea]', 675),
		t_country_obj(q'[バミューダ諸島]',  q'[Bermuda]', 1),
		t_country_obj(q'[バミューダ諸島]',  q'[Bermuda]', 441),
		t_country_obj(q'[パラオ]',  q'[Palau]', 680),
		t_country_obj(q'[パラグアイ]',  q'[Paraguay]', 595),
		t_country_obj(q'[バルバドス]',  q'[Barbados]', 1),
		t_country_obj(q'[バルバドス]',  q'[Barbados]', 246),
		t_country_obj(q'[パレスチナ]',  q'[Palestine]', 970),
		t_country_obj(q'[ハワイ]',  q'[Hawaii]', 1),
		t_country_obj(q'[ハワイ]',  q'[Hawaii]', 808),
		t_country_obj(q'[ハンガリー]',  q'[Hungary]', 36),
		t_country_obj(q'[バングラデシュ]',  q'[Bangladesh]', 880),
		t_country_obj(q'[フィジー]',  q'[Fiji]', 679),
		t_country_obj(q'[フィリピン]',  q'[Philippines]', 63),
		t_country_obj(q'[フィンランド]',  q'[Finland]', 358),
		t_country_obj(q'[ブータン]',  q'[Bhutan]', 975),
		t_country_obj(q'[プエルトリコ]',  q'[Puerto Rico]', 1),
		t_country_obj(q'[プエルトリコ]',  q'[Puerto Rico]', 787),
		t_country_obj(q'[プエルトリコ]',  q'[Puerto Rico]', 939),
		t_country_obj(q'[フェロー諸島]',  q'[Faroe Islands]', 298),
		t_country_obj(q'[フォークランド諸島]',  q'[Falkland Is.]', 500),
		t_country_obj(q'[ブラジル]',  q'[Brazil]', 55),
		t_country_obj(q'[フランス]',  q'[France]', 33),
		t_country_obj(q'[フランス領ギアナ]',  q'[French Guiana]', 594),
		t_country_obj(q'[フランス領ポリネシア]',  q'[French Polynesia]', 689),
		t_country_obj(q'[ブルガリア]',  q'[Bulgaria]', 359),
		t_country_obj(q'[ブルキナファソ]',  q'[Burkina Faso]', 226),
		t_country_obj(q'[ブルネイ]',  q'[Brunei]', 673),
		t_country_obj(q'[ブルンジ]',  q'[Burundi]', 257),
		t_country_obj(q'[ベトナム]',  q'[Viet Nam]', 84),
		t_country_obj(q'[ベナン]',  q'[Benin]', 229),
		t_country_obj(q'[ベネズエラ]',  q'[Venezuela]', 58),
		t_country_obj(q'[ベラルーシ]',  q'[Belarus]', 375),
		t_country_obj(q'[ベリーズ]',  q'[Belize]', 501),
		t_country_obj(q'[ペルー]',  q'[Peru]', 51),
		t_country_obj(q'[ベルギー]',  q'[Belgium]', 32),
		t_country_obj(q'[ポーランド]',  q'[Poland]', 48),
		t_country_obj(q'[ボスニア・ヘルツェゴビナ]',  q'[Bosnia & Herzegovina]', 387),
		t_country_obj(q'[ボツワナ]',  q'[Botswana]', 267),
		t_country_obj(q'[ボリビア]',  q'[Bolivia]', 591),
		t_country_obj(q'[ポルトガル]',  q'[Portugal]', 351),
		t_country_obj(q'[ホンジュラス]',  q'[Honduras]', 504),
		t_country_obj(q'[マーシャル諸島]',  q'[Marshall Is.]', 692),
		t_country_obj(q'[マカオ]',  q'[Macao]', 853),
		t_country_obj(q'[マダガスカル]',  q'[Madagascar]', 261),
		t_country_obj(q'[マディラ諸島]',  q'[Madeira]', 351),
		t_country_obj(q'[マラウイ]',  q'[Malawi]', 265),
		t_country_obj(q'[マリ]',  q'[Mali]', 223),
		t_country_obj(q'[マルタ]',  q'[Malta]', 356),
		t_country_obj(q'[マルチニーク島]',  q'[Martinique]', 596),
		t_country_obj(q'[マレーシア]',  q'[Malaysia]', 60),
		t_country_obj(q'[ミクロネシア連邦]',  q'[Micronesia]', 691),
		t_country_obj(q'[ミャンマー]',  q'[Myanmar]', 95),
		t_country_obj(q'[メキシコ]',  q'[Mexico]', 52),
		t_country_obj(q'[モーリシャス]',  q'[Mauritius]', 230),
		t_country_obj(q'[モーリタニア]',  q'[Mauritania]', 222),
		t_country_obj(q'[モザンビーク]',  q'[Mozambique]', 258),
		t_country_obj(q'[モナコ]',  q'[Monaco]', 377),
		t_country_obj(q'[モルディブ]',  q'[Maldives]', 960),
		t_country_obj(q'[モルドバ]',  q'[Moldova]', 373),
		t_country_obj(q'[モロッコ]',  q'[Morocco]', 212),
		t_country_obj(q'[モンゴル]',  q'[Mongolia]', 976),
		t_country_obj(q'[モンセラット]',  q'[Montserrat]', 1),
		t_country_obj(q'[モンセラット]',  q'[Montserrat]', 664),
		t_country_obj(q'[モンテネグロ]',  q'[Montenegro]', 382),
		t_country_obj(q'[ヨルダン]',  q'[Jordan]', 962),
		t_country_obj(q'[ラオス]',  q'[Laos]', 856),
		t_country_obj(q'[ラトビア]',  q'[Latvia]', 371),
		t_country_obj(q'[リトアニア]',  q'[Lithuania]', 370),
		t_country_obj(q'[リビア]',  q'[Libya]', 218),
		t_country_obj(q'[リヒテンシュタイン]',  q'[Liechtenstein]', 423),
		t_country_obj(q'[リベリア]',  q'[Liberia]', 231),
		t_country_obj(q'[ルーマニア]',  q'[Romania]', 40),
		t_country_obj(q'[ルクセンブルグ]',  q'[Luxembourg]', 352),
		t_country_obj(q'[ルワンダ]',  q'[Rwanda]', 250),
		t_country_obj(q'[レソト]',  q'[Lesotho]', 266),
		t_country_obj(q'[レバノン]',  q'[Lebanon]', 961),
		t_country_obj(q'[レユニオン]',  q'[Reunion]', 262),
		t_country_obj(q'[ロシア連邦]',  q'[Russian Fed.]', 7),
		t_country_obj(q'[英領バージン諸島]',  q'[British Virgin Is.]', 1),
		t_country_obj(q'[英領バージン諸島]',  q'[British Virgin Is.]', 284),
		t_country_obj(q'[韓国]',  q'[Korea(Rep. of)]', 82),
		t_country_obj(q'[香港]',  q'[Hong Kong]', 852),
		t_country_obj(q'[赤道ギニア]',  q'[Equatorial Guinea]', 240),
		t_country_obj(q'[台湾]',  q'[Taiwan]', 886),
		t_country_obj(q'[中央アフリカ]',  q'[Central Africa]', 236),
		t_country_obj(q'[中国]',  q'[China]', 86),
		t_country_obj(q'[東ティモール]',  q'[East Timor]', 670),
		t_country_obj(q'[南アフリカ]',  q'[South Africa]', 27),
		t_country_obj(q'[南スーダン]',  q'[South Sudan]', 211),
		t_country_obj(q'[日本]',  q'[Japan]', 81),
		t_country_obj(q'[米領サモア]',  q'[American Samoa]', 1),
		t_country_obj(q'[米領サモア]',  q'[American Samoa]', 684),
		t_country_obj(q'[米領バージン諸島]',  q'[American Virgin Is.]', 1),
		t_country_obj(q'[米領バージン諸島]',  q'[American Virgin Is.]', 340),
		t_country_obj(q'[北マケドニア]',  q'[North Macedonia]', 389),
		t_country_obj(q'[北朝鮮 (朝鮮民主主義人民共和国)]',  q'[Korea(Demo.)]', 850)

	);
    cno(v_country_data);    
END;
/
